default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  user: postgres


development:
  <<: *default
  database: OneBitNewExchange_development


test:
  <<: *default
  database: OneBitNewExchange_test


production:
  <<: *default
  database: OneBitNewExchange_production
  username: OneBitNewExchange
  password: <%= ENV['EXCHANGE_DATABASE_PASSWORD'] %>
